CREATE DATABASE IF NOT EXISTS calendar;

CREATE TABLE IF NOT EXISTS calendar.migrations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
