USE calendar;

CREATE TABLE IF NOT EXISTS materias (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  color VARCHAR(6) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS horarios (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  day INT NOT NULL,
  start TIME NOT NULL,
  finish TIME NOT NULL,
  materia_id INT UNSIGNED,
  CONSTRAINT fk_Materia_H
  FOREIGN KEY (materia_id)
  REFERENCES materias(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS events_types (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS events (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  materia_id INT UNSIGNED,
  type INT UNSIGNED,
  date DATE NOT NULL,
  CONSTRAINT fk_Materia_E
  FOREIGN KEY (materia_id)
  REFERENCES materias(id),
  CONSTRAINT fk_Event_T
  FOREIGN KEY (type)
  REFERENCES events_types(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS periods (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  type INT UNSIGNED,
  start DATE NOT NULL,
  end DATE NOT NULL,
  details VARCHAR(100),
  suspension BOOLEAN NOT NULL,
  CONSTRAINT fk_Event_P
  FOREIGN KEY (type)
  REFERENCES events_types(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS feriados (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL,
  details VARCHAR(100) NOT NULL,
  type VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS migrations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
