CREATE TABLE IF NOT EXISTS events (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  materia_id INT UNSIGNED,
  type INT UNSIGNED,
  date DATE NOT NULL,
  active BOOL NOT NULL DEFAULT TRUE,
  CONSTRAINT fk_Materia_E
  FOREIGN KEY (materia_id)
  REFERENCES materias(id),
  CONSTRAINT fk_Event_T
  FOREIGN KEY (type)
  REFERENCES events_types(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS periods (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  type INT UNSIGNED,
  start DATE NOT NULL,
  end DATE NOT NULL,
  details VARCHAR(100),
  suspension BOOLEAN NOT NULL,
  active BOOL NOT NULL DEFAULT TRUE,
  CONSTRAINT fk_Event_P
  FOREIGN KEY (type)
  REFERENCES events_types(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS feriados (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL,
  details VARCHAR(100) NOT NULL,
  type VARCHAR(100) NOT NULL,
  active BOOL NOT NULL DEFAULT TRUE
) ENGINE=InnoDB;
