CREATE TABLE IF NOT EXISTS materias (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  color VARCHAR(6) NOT NULL,
  active BOOL NOT NULL DEFAULT TRUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS horarios (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  day INT NOT NULL,
  start TIME NOT NULL,
  finish TIME NOT NULL,
  materia_id INT UNSIGNED,
  active BOOL NOT NULL DEFAULT TRUE,
  CONSTRAINT fk_Materia_H
  FOREIGN KEY (materia_id)
  REFERENCES materias(id)
) ENGINE=InnoDB;

