CREATE TABLE IF NOT EXISTS backup (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  temporary BOOL DEFAULT FALSE
) ENGINE=InnoDB;
